# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 5 sdk'
  inputs:
    packageType: 'sdk'
    version: '5.x'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: './SampleTests/SampleTests.csproj'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
  continueOnError: false

- task: DotNetCoreCLI@2
  displayName: 'Generate NuGet Package'
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    packagesToPack: './TestHelpers/TestHelpers.csproj'
    outputDir: '$(Build.ArtifactStagingDirectory)/packages'
    nobuild: true
    versioningScheme: byPrereleaseNumber
    majorVersion: '1'
    minorVersion: '1'
    patchVersion: '4'
